/**********************************************************************************
Desarrollado por: Cloud Solutions
Autor: Rodrigo López (RL)
Proyecto: Naviera Austral
Descripción: Clase para guardar parámetros de busqueda de Tarifas de clase NAV_Tarificador
---------------------------------------------------------------------------------
Versión Fecha        Autor    Descripción
---------------------------------------------------------------------------------
1.0     01-12-2021   RL       Creación de la Clase.
***********************************************************************************/

public class NAV_Tarifa_Return  {
	public String IdParametroTarifa{get;set;}
    public String IdDetalleReserva{get;set;}
    public String Mensaje{get;set;}
}